server:
  host: localhost
  port: 8081

database:
  host: localhost
  port: 5432
  username: sachin
  password: 123456
  dbname: mydb

rateLimitConfig:
  redis:
    host: 0.0.0.0
    port: 6379
  rateLimit:
    - key: /employees
      rate: 3
      unit: minute
    - key: /relative-url-02
      rate: 10
      unit: second